#!/bin/bash

# Uninstall unnecessary applications
apps_to_uninstall=(
    "net.bat.store"
    "com.transsion.kolun.assistant"
    "com.google.android.apps.googleassistant"
    "com.google.android.calendar"
    "com.transsion.deskclock"
    "com.transsion.compass"
    "com.transsion.filemanagerx"
    "com.skyroam.silverhelper"
    "com.google.android.googlequicksearchbox"
    "com.talpa.hibrowser"
    "com.zaz.translate"
    "com.transsion.childmode"
    "com.transsion.mol"
    "com.transsion.manualguide"
    "tech.palm.id"
    "com.transsnet.store"
    "com.transsion.letswitch"
    "com.transsion.phonemaster"
    "com.google.android.apps.photos"
    "com.transsion.powercenter"
    "com.transsion.batterylab"
    "com.transsion.batterylab.icon"
    "com.idea.questionnaire"
    "com.transsion.sk"
    "com.transsion.wezone"
    "com.trassion.infinix.xclub"
    "com.infinix.xpark"
    "com.talpa.share"
    "com.transsion.wifiplaytogether"
    "com.google.android.youtube"
    "com.google.android.apps.youtube.music"
    "com.transsion.zahooc"
    "com.transsion.carlcare"
    "com.android.contacts"
    "com.transsion.dtsaudio"
    "com.transsion.scanningrecharger"
    "com.rlk.weathers"
    "com.transsion.healthlife"
    "com.transsion.fmradio"
    "com.theme.icondefaultshape_freefire"
)

for app in "${apps_to_uninstall[@]}"; do
    pm uninstall --user 0 "$app"
done
